/*11) LISTAR O CODIGO E A DESCRIÇAO DOS PRODUTOS QUE TENHAM VALOR UNITARIO NA FAIXA DE R$0.32 ATÉ R$2.00*/

SELECT Cod_produto, DescProduto, ValorUnitario FROM Produto WHERE ValorUnitario between '0.32' AND '2.00'
