/*06) LISTAR O NUMERO DO PEDIDO , O CODIGO DO PRODUTO E A QUANTIDADE DOS ITENS DO PEDIDO COM A QUANTIDADE IGUAL A 35 DA TABELA ITEM _PEDIDO*/

SELECT Num_Pedido, Cod_Produto, Qtde_Produto FROM Item_Pedido WHERE Qtde_Produto = 35
