INSERT INTO `prontuario` (`id`, `id_paciente`, `id_consulta`, `descricao`, `data_registro`, `medico_responsavel`, `observacoes`) VALUES
(121, 1, 61, 'Paciente relatou dor no peito. Foi solicitado exame de sangue e eletrocardiograma.', '2023-10-01', 'Dr. João Silva', 'Paciente deve retornar em 15 dias.'),
(122, 2, 62, 'Paciente apresentou manchas na pele. Foi receitado creme hidratante e protetor solar.', '2023-10-02', 'Dra. Maria Oliveira', 'Paciente deve evitar exposição ao sol.'),
(123, 3, 63, 'Paciente com fratura no braço. Foi imobilizado e encaminhado para fisioterapia.', '2023-10-03', 'Dr. Carlos Souza', 'Paciente deve retornar em 30 dias.'),
(124, 4, 64, 'Paciente com febre alta. Foi receitado antitérmico e repouso.', '2023-10-04', 'Dra. Ana Costa', 'Paciente deve retornar em 7 dias.'),
(125, 5, 65, 'Paciente relatou dor de cabeça. Foi solicitado exame de imagem.', '2023-10-05', 'Dr. Pedro Rocha', 'Paciente deve retornar em 10 dias.'),
(126, 6, 66, 'Paciente com tontura. Foi solicitado exame de sangue e avaliação neurológica.', '2023-10-06', 'Dra. Fernanda Lima', 'Paciente deve evitar movimentos bruscos.'),
(127, 7, 67, 'Paciente com ansiedade. Foi receitado ansiolítico e encaminhado para psicoterapia.', '2023-10-07', 'Dr. Ricardo Alves', 'Paciente deve retornar em 14 dias.'),
(128, 8, 68, 'Paciente com insônia. Foi receitado medicamento para sono e orientações de higiene do sono.', '2023-10-08', 'Dra. Juliana Santos', 'Paciente deve retornar em 21 dias.'),
(129, 9, 69, 'Paciente com dor nas costas. Foi solicitado exame de imagem e encaminhado para fisioterapia.', '2023-10-09', 'Dr. Marcelo Fernandes', 'Paciente deve evitar esforço físico.'),
(130, 10, 70, 'Paciente com pressão alta. Foi receitado anti-hipertensivo e orientações alimentares.', '2023-10-10', 'Dra. Patrícia Gonçalves', 'Paciente deve retornar em 30 dias.'),
(131, 11, 71, 'Paciente com dor no joelho. Foi solicitado exame de imagem e encaminhado para ortopedia.', '2023-10-11', 'Dr. Lucas Mendes', 'Paciente deve evitar atividades de impacto.'),
(132, 12, 72, 'Paciente com dor nas articulações. Foi receitado anti-inflamatório e encaminhado para reumatologia.', '2023-10-12', 'Dra. Camila Ribeiro', 'Paciente deve retornar em 15 dias.'),
(133, 13, 73, 'Paciente com febre persistente. Foi solicitado exame de sangue e urina.', '2023-10-13', 'Dr. Gustavo Nunes', 'Paciente deve retornar em 7 dias.'),
(134, 14, 74, 'Paciente com dor abdominal. Foi solicitado ultrassom e encaminhado para gastroenterologia.', '2023-10-14', 'Dra. Larissa Martins', 'Paciente deve evitar alimentos pesados.'),
(135, 15, 75, 'Paciente relatou dor no peito. Foi solicitado exame de sangue e eletrocardiograma.', '2023-10-15', 'Dr. Bruno Carvalho', 'Paciente deve retornar em 15 dias.'),
(136, 16, 76, 'Paciente apresentou manchas na pele. Foi receitado creme hidratante e protetor solar.', '2023-10-16', 'Dra. Vanessa Dias', 'Paciente deve evitar exposição ao sol.'),
(137, 17, 77, 'Paciente com fratura no braço. Foi imobilizado e encaminhado para fisioterapia.', '2023-10-17', 'Dr. Rafael Castro', 'Paciente deve retornar em 30 dias.'),
(138, 18, 78, 'Paciente com febre alta. Foi receitado antitérmico e repouso.', '2023-10-18', 'Dra. Simone Araújo', 'Paciente deve retornar em 7 dias.'),
(139, 19, 79, 'Paciente relatou dor de cabeça. Foi solicitado exame de imagem.', '2023-10-19', 'Dr. Eduardo Lima', 'Paciente deve retornar em 10 dias.'),
(140, 20, 80, 'Paciente com tontura. Foi solicitado exame de sangue e avaliação neurológica.', '2023-10-20', 'Dra. Mariana Rocha', 'Paciente deve evitar movimentos bruscos.'),
(141, 21, 81, 'Paciente com ansiedade. Foi receitado ansiolítico e encaminhado para psicoterapia.', '2023-10-21', 'Dr. Felipe Almeida', 'Paciente deve retornar em 14 dias.'),
(142, 22, 82, 'Paciente com insônia. Foi receitado medicamento para sono e orientações de higiene do sono.', '2023-10-22', 'Dra. Renata Barbosa', 'Paciente deve retornar em 21 dias.'),
(143, 23, 83, 'Paciente com dor nas costas. Foi solicitado exame de imagem e encaminhado para fisioterapia.', '2023-10-23', 'Dr. André Pereira', 'Paciente deve evitar esforço físico.'),
(144, 24, 84, 'Paciente com pressão alta. Foi receitado anti-hipertensivo e orientações alimentares.', '2023-10-24', 'Dra. Carolina Freitas', 'Paciente deve retornar em 30 dias.'),
(145, 25, 85, 'Paciente com dor no joelho. Foi solicitado exame de imagem e encaminhado para ortopedia.', '2023-10-25', 'Dr. Diego Costa', 'Paciente deve evitar atividades de impacto.');
